In [1]:
'''
QUESTION 1
'''
import pandas as pd
# importing the datasets
df1 = pd.read_csv('Olympics_dataset1.csv')
df2 = pd.read_csv('Olympics_dataset2.csv')

# merging the datasets
df = pd.merge(left=df1, right=df2, on=None, left_on='Team', right_on='Team')

# dropping the first row of the datasets
df.drop(df.index[0], inplace=True)

# dropping the unsued columns
df.drop(['Combined Total', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',], axis='columns', inplace=True)

# creating a dict to map the renaming of columns
rename_dict = {
    "Team": "Country",
    "Unnamed: 1": "summer_rubbish",
    "Summer Games": "summer_participation",
    "Unnamed: 3_x": "summer_gold",
    "Unnamed: 4_x": "summer_silver",
    "Unnamed: 5_x": "summer_bronze",
    "Unnamed: 6": "summer_total",
    "Winter Games": "winter_participation",
    "Unnamed: 2": "winter_gold",
    "Unnamed: 3_y": "winter_silver",
    "Unnamed: 4_y": "winter_bronze",
    "Unnamed: 5_y": "winter_total",
}

# renaming the columns
df.rename(columns=rename_dict, inplace=True)

# removing the 'Totals' row from the dataframe
df = df[df.Country != 'Totals']
#df.drop(df.index[df.shape[0]-1], inplace=True)

# printing first five rows of dataframe
print(df.head().to_string())

'''
QUESTION 2
'''

# function for removing the words in brackets
def remove_words_in_brackets(cell):
    for i in range(len(cell)):
        if cell[i] == '(':
            return cell[:i]
    return cell

# removing words in brackets
df['Country'] = df['Country'].map(remove_words_in_brackets)

# setting index as Country
df.set_index('Country', inplace=True)

# removing the undesired columns
df.drop(['summer_rubbish', 'summer_total', 'winter_total'], axis='columns', inplace=True)

# printing the data
df.head().to_string()

'''
QUESTION 3
'''

# dropping rows with na values
df.dropna(how='all', inplace=True)

# printing values
df.tail(10).to_string()


'''
QUESTION 4
'''

# function for casting string to integer
def convert_int(n):
    if ',' in n:
        n = n.replace(',', '')
        return int(n)
    else:
        return int(n)

# converting string into numbers
df['summer_gold'] = df['summer_gold'].map(convert_int)

# printing the country with max gold
df[df['summer_gold'] == df['summer_gold'].max()].index[0]

# converting string into numbers
df['winter_gold'] = df['winter_gold'].map(convert_int)

# finding the max difference
max_diff = abs(df['winter_gold'] - df['summer_gold']).max()

# finding the name of the country
print(df[abs(df['winter_gold'] - df['summer_gold']) == max_diff].index[0], max_diff)
'''
QUESTION 6
'''
# changing the str values to numberic values
df['summer_silver'] = df['summer_silver'].map(convert_int)
df['summer_bronze'] = df['summer_bronze'].map(convert_int)
df['winter_silver'] = df['winter_silver'].map(convert_int)
df['winter_bronze'] = df['winter_bronze'].map(convert_int)

# creating a new column with sum of all medals
df['total'] = df['summer_gold'] + df['summer_silver'] + df['summer_bronze'] + df['winter_gold'] + df['winter_silver'] + df['winter_bronze']

# printing the values
print(df.sort_values(by='total', ascending=False).head().to_string())
print(df.sort_values(by='total', ascending=False).tail().to_string())

                    Country summer_rubbish summer_participation summer_gold summer_silver summer_bronze summer_total winter_participation winter_gold winter_silver winter_bronze winter_total
1         Afghanistan (AFG)            BLA                   14           0             0             2            2                    0           0             0             0            0
2             Algeria (ALG)            BLA                   13           5             4             8           17                    3           0             0             0            0
3           Argentina (ARG)            BLA                   24          21            25            28           74                   19           0             0             0            0
4             Armenia (ARM)            BLA                    6           2             6             6           14                    7           0             0             0            0
5   Australasia (ANZ) [ANZ]            BLA                    2           3             4             5           12                    0           0             0             0            0
 United States  917
                summer_participation  summer_gold  summer_silver  summer_bronze winter_participation  winter_gold  winter_silver  winter_bronze  total
Country
 United States                    27         1022            795            705                   23          105            110             90   2827
 Soviet Union                      9          395            319            296                    9           78             57             59   1204
 Great Britain                    28          263            295            291                   23           11              4             16    880
 Germany                          16          191            194            230                   12           92             88             60    855
 France                           28          212            241            263                   23           36             35             53    840
           summer_participation  summer_gold  summer_silver  summer_bronze winter_participation  winter_gold  winter_silver  winter_bronze  total
Country
 Jordan                      10            1              0              0                    0            0              0              0      1
 Djibouti                     8            0              0              1                    0            0              0              0      1
 Cyprus                      10            0              1              0                   11            0              0              0      1
 Sudan                       12            0              1              0                    0            0              0              0      1
 Senegal                     14            0              1              0                    5            0              0              0      1

In [4]:
# convert participation from string to int
df['summer_participation'] = df['summer_participation'].map(convert_int)

In [13]:
# make a new column in dataframe with the rule
df['rate'] = (df['summer_gold']*5 + df['summer_silver']*3 + df['summer_bronze'])/df['summer_participation']

# printing the values
print(df.sort_values(by='rate', ascending=False).head()['rate'].to_string())

Country
 Unified Team      368.000000
 Soviet Union      358.666667
 United States     303.703704
 East Germany      255.800000
 Russia            211.666667